name: Deploy to GCE
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GCE by using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/farisjr/app
          git pull origin production
          docker stop myApp
          docker rm myApp
          cd project
          docker build -t my-app:latest .
          docker run -d -e "HTTP_PORT=:80" -p 80:80 --name myApp my-app:latest
